# Generated by Django 5.0 on 2026-05-01 19:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('accuracy', models.FloatField(blank=True, help_text='Accuracy in meters', null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, help_text='Speed in m/s', null=True)),
                ('heading', models.FloatField(blank=True, help_text='Direction in degrees', null=True)),
                ('battery_level', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_charging', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'locations',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SafeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_code', models.CharField(db_index=True, max_length=6)),
                ('name', models.CharField(max_length=100)),
                ('zone_type', models.CharField(choices=[('home', 'Uy'), ('school', 'Maktab'), ('relative', 'Qarindosh uyi'), ('other', 'Boshqa')], default='other', max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius', models.IntegerField(default=100, help_text='Radius in meters')),
                ('is_active', models.BooleanField(default=True)),
                ('notify_on_enter', models.BooleanField(default=True)),
                ('notify_on_exit', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_zones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'safe_zones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZoneEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('enter', 'Kirdi'), ('exit', 'Chiqdi')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notified', models.BooleanField(default=False)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_events', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='location.safezone')),
            ],
            options={
                'db_table': 'zone_events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['user', '-timestamp'], name='locations_user_id_f806ac_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['timestamp'], name='locations_timesta_8e7a14_idx'),
        ),
        migrations.AddIndex(
            model_name='zoneevent',
            index=models.Index(fields=['user', '-timestamp'], name='zone_events_user_id_8a6572_idx'),
        ),
        migrations.AddIndex(
            model_name='zoneevent',
            index=models.Index(fields=['zone', '-timestamp'], name='zone_events_zone_id_3115e2_idx'),
        ),
    ]
