# Generated by Django 5.0 on 2026-05-01 19:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_type', models.CharField(choices=[('website', 'Veb-sayt'), ('keyword', "Kalit so'z"), ('category', 'Kategoriya')], max_length=20)),
                ('value', models.CharField(help_text='URL, keyword, or category', max_length=500)),
                ('category', models.CharField(blank=True, choices=[('adult', 'Kattalar uchun'), ('violence', "Zo'ravonlik"), ('gambling', 'Qimor'), ('drugs', 'Giyohvand moddalar'), ('weapons', 'Qurol'), ('hate', 'Nafrat'), ('other', 'Boshqa')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_filters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'content_filters',
            },
        ),
        migrations.CreateModel(
            name='ScreenTimeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'screen_time_sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='AppUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=200)),
                ('package_name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('duration_seconds', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('date', models.DateField(db_index=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_usage',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-date'], name='app_usage_user_id_7c0467_idx'), models.Index(fields=['date'], name='app_usage_date_f9445a_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlockedApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=200)),
                ('package_name', models.CharField(max_length=200)),
                ('reason', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps_blocked', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_apps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blocked_apps',
                'unique_together': {('user', 'package_name')},
            },
        ),
        migrations.CreateModel(
            name='BlockedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=20)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('app_name', models.CharField(blank=True, max_length=200)),
                ('reason', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blocked_content',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='blocked_con_user_id_ba8156_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScreenTimeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Dushanba'), ('tuesday', 'Seshanba'), ('wednesday', 'Chorshanba'), ('thursday', 'Payshanba'), ('friday', 'Juma'), ('saturday', 'Shanba'), ('sunday', 'Yakshanba')], max_length=10)),
                ('start_time', models.TimeField(help_text='Ruxsat berilgan vaqt boshlanishi')),
                ('end_time', models.TimeField(help_text='Ruxsat berilgan vaqt tugashi')),
                ('max_duration_minutes', models.IntegerField(help_text='Maksimal foydalanish vaqti (daqiqalarda)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1440)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_screen_rules', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_time_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'screen_time_rules',
                'unique_together': {('user', 'day_of_week')},
            },
        ),
    ]
